* company-eshell-autosuggest
[[http://melpa.milkbox.net/#/company-eshell-autosuggest][file:http://melpa.milkbox.net/packages/company-eshell-autosuggest-badge.svg]]
[[https://stable.melpa.org/#/company-eshell-autosuggest][file:https://stable.melpa.org/packages/company-eshell-autosuggest-badge.svg]]
[[https://www.gnu.org/licenses/gpl-3.0.txt][file:https://img.shields.io/badge/license-GPL_3-green.svg]]

Fish-like history autosuggestions in eshell

See [[http://whyarethingsthewaytheyare.com/fishlike-autosuggestions-in-eshell/][my blog post]] for an example.

** Usage
This package assumes you use something other than company for eshell completion
(e.g. ~eshell-pcomplete~, ~completion-at-point~, ~helm-esh-pcomplete~).
~company-mode~ is used solely as a mechanism for history autosuggestions.

You can enable the autosuggestions with:
#+begin_src emacs-lisp
(add-hook 'eshell-mode-hook #'company-eshell-autosuggest-mode)
#+end_src

*** Selection key
~<right>~ is used to select the suggestion by default. You can change this or
add additional keys by modifying the variable
~company-eshell-autosuggest-selection-keys~.

*** Delay
Delay defaults to 0 seconds. This is most like fish shell's instant history
autosuggestions, but can be customized through the variable
~company-eshell-autosuggest-delay~.

** Installation
This package is on melpa. If you have melpa in your package repositories, you
can use ~M-x RET package-install RET company-eshell-autosuggest~ or install
with [[https://github.com/jwiegley/use-package][use-package]]:
#+begin_src emacs-lisp
(use-package company-eshell-autosuggest
  :ensure t)
#+end_src

Alternatively, consider installing with [[https://github.com/raxod502/straight.el][straight.el]] or [[https://github.com/quelpa/quelpa-use-package][quelpa-use-package]].

Otherwise, download the files to somewhere on your load path, and require
company-eshell-autosuggest:
#+begin_src emacs-lisp
(require 'company-eshell-autosuggest)
#+end_src

